### ISSUE TITLE
[Astillero] Añadir permiso por cada aprobación individual de una cotización

### ISSUE THREAD

**Issue by EduardoHidalgo** [MarinaVVsoftware/Novonautica-old#600]
Las cotizaciones de astillero sufren 2 aprobaciones antes de convertirse en ODT:

- Aprobación por parte de negocio
- Aprobación por parte del cliente

Dentro del sistema de permisos de Novonautica hay un permiso que engloba ambas aprobaciones. El Fix trata de separar este permiso en 2 permisos separados, cada uno para cada aprobación.

Adicionalmente debe ser posible que exista un usuario con los mínimos permisos necesarios (pero posibles) para ver la lista de cotizaciones, Aprobar por parte de negocio, y únicamente realizar dichas actividades.

> El objetivo es que existan 2 usuarios (Admin Astillero y Jefe de Patio) donde donde **solo el Jefe de Patio** pueda **aprobar por parte de negocio** pero sin permiso de ninguna otra funcionalidad.

**Comment by manuelGTZ97** [comment]
Pendiente para realizar pruebas.

**Comment by EduardoHidalgo** [comment]
Hay un error de permisos al realizar el test sobre beta.novonautica.com, con un usuario con los permisos adecuados según la lógica de negocio. Tanto la validación como aceptación marcan error 403.

![image](https://user-images.githubusercontent.com/30780192/62321399-28770d00-b468-11e9-8bae-49f01a867a4d.png)


![image](https://user-images.githubusercontent.com/30780192/62321387-1c8b4b00-b468-11e9-99ba-a18d179edc4f.png)

![image](https://user-images.githubusercontent.com/30780192/62321446-447aae80-b468-11e9-859c-48be54d281a5.png)

Idealmente un usuario con esa configuración de permisos **no debería ver el botón de "Aceptar"** que representa la validación por parte del cliente. El **botón de "Validar" si debe verlo** y hacer uso de su funcionalidad.

**Comment by EduardoHidalgo** [comment]
- [ ] añadir un checkbox para solicitar o no la aprobación de jefe de patio
